### ISSUE TITLE
Service Detail View

### ISSUE THREAD

**Issue by filopedraz** [premAI-io/prem-registry-ui#3]
### Description

Instead of a modal, we should have a separate page for SEO purposes. Make sure to include metadata.

### Frames

<img width="693" alt="image" src="https://github.com/premAI-io/prem-registry-ui/assets/29598954/e5136620-f987-4f29-8f00-5191bc583fd7">

If service.banner tag is present, 

<img width="646" alt="image" src="https://github.com/premAI-io/prem-registry-ui/assets/29598954/72357da3-6b80-4bc2-9b26-9e46862fa7b8">

**Comment by Janaka-Steph** [comment]
While it was not the case years before, current search engines are now capable of executing JavaScript to a certain extent when crawling and indexing web pages. Google's web crawler, known as Googlebot, has improved its ability to understand and process JavaScript-based content. So, while server-side rendering would be the ideal technique, simply moving each service detail view to its own page should be enough.
